### PR TITLE
swap out yara pattern scanning for binary regexps

### LINKED ISSUE #23: GoReSym binary is linked with libyara.so.10 on Linux
When I tried to run it on Ubuntu 22.04, I get an error message that `libyara.so.10` is missing. I installed the `libyara-dev` with apt, but it did not fix the problem, since the one that comes is `libyara.so.8`. Manually building the libyara following this guide https://yara.readthedocs.io/en/stable/gettingstarted.html generates a `libyara.so.10` and it works fine. 

Does GoReSym actually require the latest features of yara? Could it be built with an earlier version of it so that it runs out of the box on Ubuntu? Or, since yara comes with a quite permissive license (https://github.com/VirusTotal/yara/blob/master/COPYING), could GoReSym statically link with libyara.so.10?

### LINKED ISSUE #29: remove dependency on yara
yara is currently used as a pattern matching engine to find code sequences here:
https://github.com/mandiant/GoReSym/blob/f2009bd92819df2f69d74c4a32f1300be284a4fa/objfile/scanner.go

however, yara is written in C and has to be linked to this Go project. the compilation, build, and distribution is tricky; see #23 #24 and #27 for issues influenced by this complexity.

the patterns that are passed to yara are pretty simple - they could be trivially converted to binary regular expressions since there's no use of yara's `condition` logic.

the Go `regexp` module doesn't support binary regexes; however, the https://github.com/rsc/binaryregexp module does, and its easy to use. we should consider migrating from yara to binaryregexp to keep GoReSym pure-Go and therefore easier to build and distribute.

here's an example test demonstrating the translation from a yara pattern to a binaryregexp:

```go
package main

import (
	"testing"

	"rsc.io/binaryregexp"
)

func TestBinaryRegex(t *testing.T) {
	t.Run("basic non-UTF-8 data", func(t *testing.T) {
		r := binaryregexp.MustCompile(`\xfd\xe3`)

		if !r.MatchString("\xfd\xe2") {
			t.Errorf("failed to match non-UTF-8 data")
		}
	})

	// x64firstmoduledata
	// $sig = { 48 8D 0? ?? ?? ?? ?? EB ?? 48 8? 8? ?? 02 00 00 66 0F 1F 44 00 00 }
	t.Run("x64firstmoduledata", func(t *testing.T) {
		r := binaryregexp.MustCompile(`\x48\x8D[\x00-\x0F]....\xEB.\x48[\x80-\x8F][\x80-\x8F].\x02\x00\x00\x66\x0F\x1F\x44\x00\x00`)

		// 0x000000000044D80A: 48 8D 0D 8F DA 26 00                    lea     rcx, runtime_firstmoduledata
		// 0x000000000044D811: EB 0D                                   jmp     short loc_44D820
		// 0x000000000044D813: 48 8B 89 30 02 00 00                    mov     rcx, [rcx+230h]
		// 0x000000000044D81A: 66 0F 1F 44 00 00                       nop     word ptr [rax+rax+00h]    <- always seems to be present
		if !r.Match([]byte{0x48, 0x8D, 0x0D, 0x8F, 0xDA, 0x26, 0x00, 0xEB, 0x0D, 0x48, 0x8B, 0x89, 0x30, 0x02, 0x00, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00}) {
			t.Errorf("failed to match data verbatim")
		}

		// extra bytes at start
		if !r.Match([]byte{0xFF, 0xFF, 0x48, 0x8D, 0x0D, 0x8F, 0xDA, 0x26, 0x00, 0xEB, 0x0D, 0x48, 0x8B, 0x89, 0x30, 0x02, 0x00, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00}) {
			t.Errorf("failed to match data with prefix bytes")
		}

		// extra bytes at end
		if !r.Match([]byte{0x48, 0x8D, 0x0D, 0x8F, 0xDA, 0x26, 0x00, 0xEB, 0x0D, 0x48, 0x8B, 0x89, 0x30, 0x02, 0x00, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00, 0xFF, 0xFF}) {
			t.Errorf("failed to match data with postfix bytes")
		}

		// first byte doesn't match
		if r.Match([]byte{0xFF, 0x8D, 0x0D, 0x8F, 0xDA, 0x26, 0x00, 0xEB, 0x0D, 0x48, 0x8B, 0x89, 0x30, 0x02, 0x00, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00}) {
			t.Errorf("unexpected match")
		}

		// byte 2 range is different
		if !r.Match([]byte{0x48, 0x8D, 0x00, 0x8F, 0xDA, 0x26, 0x00, 0xEB, 0x0D, 0x48, 0x8B, 0x89, 0x30, 0x02, 0x00, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00}) {
			t.Errorf("failed to match data variant 1")
		}
		// byte 2 range is different
		if !r.Match([]byte{0x48, 0x8D, 0x0F, 0x8F, 0xDA, 0x26, 0x00, 0xEB, 0x0D, 0x48, 0x8B, 0x89, 0x30, 0x02, 0x00, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00}) {
			t.Errorf("failed to match data variant 2")
		}
	})
}
```

```console
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestBinaryRegex$ github.com/mandiant/GoReSym

ok  	github.com/mandiant/GoReSym	0.002s
```

### PR DESCRIPTION
**Pull request by williballenthin**
closes #29
closes #23

### CODE REVIEW

**Comment by williballenthin** [comment]
tests pass when i run them locally.

**Comment by williballenthin** [comment]
unfortunately the performance of the binaryregexp is worse than yara. in the same environment, the test cases on master run in 67s while this PR takes 346 (5x). 

only now am i seeing that Go's regular expression implementation is really slow: https://github.com/mariomka/regex-benchmark#performance

there are certainly some optimizations we can make to avoid doing so much regexp scanning; i will think on it and try to propose which strategies we might try first.

**Comment by stevemk14ebr** [comment]
Awe that's too bad to hear. Unfortunately I switched to yara originally for performance reasons so this makye some sense.

**Comment by williballenthin** [comment]
one thing thats suspicious is how often the scanner routine is called:

```console
@williballenthin ➜ /workspaces/GoReSym (fix/issue-29) $ go test -v -run "^TestAllVersions/117/testproject_lin$"
findModuleInitPCHeader: len(data)= 1977516
findModuleInitPCHeader: len(data)= 1463668
findModuleInitPCHeader: len(data)= 1245252
findModuleInitPCHeader: len(data)= 1244874
findModuleInitPCHeader: len(data)= 1243622
findModuleInitPCHeader: len(data)= 1243534
findModuleInitPCHeader: len(data)= 1243534
findModuleInitPCHeader: len(data)= 880038
findModuleInitPCHeader: len(data)= 880006
findModuleInitPCHeader: len(data)= 812998
findModuleInitPCHeader: len(data)= 782262
findModuleInitPCHeader: len(data)= 589998
findModuleInitPCHeader: len(data)= 568678
findModuleInitPCHeader: len(data)= 568397
findModuleInitPCHeader: len(data)= 457639
findModuleInitPCHeader: len(data)= 436120
findModuleInitPCHeader: len(data)= 436078
findModuleInitPCHeader: len(data)= 234232
findModuleInitPCHeader: len(data)= 131110
findModuleInitPCHeader: len(data)= 95205
findModuleInitPCHeader: len(data)= 95105
findModuleInitPCHeader: len(data)= 45065
findModuleInitPCHeader: len(data)= 1977516
findModuleInitPCHeader: len(data)= 1463668
findModuleInitPCHeader: len(data)= 1245252
findModuleInitPCHeader: len(data)= 1244874
findModuleInitPCHeader: len(data)= 1243622
findModuleInitPCHeader: len(data)= 1243534
findModuleInitPCHeader: len(data)= 1243534
findModuleInitPCHeader: len(data)= 880038
findModuleInitPCHeader: len(data)= 880006
findModuleInitPCHeader: len(data)= 812998
findModuleInitPCHeader: len(data)= 782262
findModuleInitPCHeader: len(data)= 589998
findModuleInitPCHeader: len(data)= 568678
findModuleInitPCHeader: len(data)= 568397
findModuleInitPCHeader: len(data)= 457639
findModuleInitPCHeader: len(data)= 436120
findModuleInitPCHeader: len(data)= 436078
findModuleInitPCHeader: len(data)= 234232
findModuleInitPCHeader: len(data)= 131110
findModuleInitPCHeader: len(data)= 95205
findModuleInitPCHeader: len(data)= 95105
findModuleInitPCHeader: len(data)= 45065
--- PASS: TestAllVersions (7.64s)
    --- PASS: TestAllVersions/117/testproject_lin (7.48s)
PASS
ok      github.com/mandiant/GoReSym     7.658s
```

for the single ELF file the scanner is invoked 44 times. perhaps we can invoke the scanner once across the entire file and re-use the results, since they shouldn't change (GoReSym doesn't change the input file).

File: build_all.sh
Comment (stevemk14ebr) [inline build_all.sh:1]: Please restore this, we don't need the CGO linking lines anymore but this exists so that I can automatically cross-compile all versions of GoReSym for all platforms in one command when it's time to cut releases.

File: build_test_files.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@ do
     GO_TAG=$v
     GO_VER=$(echo "$GO_TAG" | tr -d '.')
     
-    rm Dockerfile.test
+    rm -f Dockerfile.test
```
Comment (stevemk14ebr) [inline build_test_files.sh:10]: thanks

File: objfile/patterns.go [hunk 2]
```diff
@@ -0,0 +1,281 @@
...
+//	{ 48 8D 0? ?? ?? ?? ?? EB ?? 48 8? 8? ?? 02 00 00 66 0F 1F 44 00 00 }
+//
+// to a regular expression string compatible with the binaryregexp module, like:
+//
+//	\x48\x8D[\x00-\x0F]....\xEB.\x48[\x80-\x8F][\x80-\x8F].\x02\x00\x00\x66\x0F\x1F\x44\x00\x00
+//
+// although this requires more code, we provide this functionality
+// because these patterns are *much* more readable than raw regular expressions,
+// we strongly value people being able to understand GoReSym's algorithm.
+func RegexpPatternFromYaraPattern(pattern string) (string, error) {
```
Comment (stevemk14ebr) [inline objfile/patterns.go:45]: This is some non-trivial work, is there a significant speedup if we hardcoded the regex style patterns rather than converting at runtime? Also: coooool

File: objfile/patterns_test.go
Comment (stevemk14ebr) [inline objfile/patterns_test.go:1]: Thanks for doing so many tests!

File: objfile/scanner.go [hunk 3]
```diff
@@ -94,111 +69,103 @@ var PPC_BE_sig = signatureModuleDataInitPPC{2, 6, `rule PPC_BEfirstmoduledata
...
+	g, e := NewBinaryRegexpGroup(map[string]string{
+		"x64":    x64sig.signature,
+		"x86":    x86sig.signature,
+		"ARM64":  ARM64_sig.signature,
+		"ARM32":  ARM32_sig.signature,
+		"PPC_BE": PPC_BE_sig.signature,
+	})
+	if e != nil {
+		// programmer error: check the patterns
+		panic(e)
```
Comment (stevemk14ebr) [inline objfile/scanner.go:93]: I don't love panicking here, I understand it's a 'static' error due to hardcoded patterns but this would break external systems that try to parse JSON output. Maybe this is a +1 for hard-coding regex patterns instead - we'd remove the error case entirely? If only Go had compile-time logic.

As this is basically an assert() we can keep it but just noting it.

**Review by stevemk14ebr — CHANGES_REQUESTED** [review]

File: build_all.sh
Comment (stevemk14ebr) [reply build_all.sh:1]: This is the only change required, looks great otherwise. Thanks for exploring the removal of yara, I'm happy with the result here :)

Comment (williballenthin) [reply build_all.sh:1]: ah, ok, sure no problem!

**Comment by williballenthin** [comment]
this PR is still too slow to merge. i'm going to work on performance optimizations before i recommend that this be merged.

i expect to be able to optimize the outer scanning loops such that the net performance change here is within 50% of today's running time. the PR is around 7x slower right now. regex scanning will remain slow, nothing we can do about that, but we'll just scan much less data. the result is a GoReSym of similar performance but no linking difficulties.

i'll do most of the perf work in other branches so as not to confuse the diff here.

File: objfile/patterns_test.go
Comment (williballenthin) [reply objfile/patterns_test.go:1]: i did my dev in test cases, and then copied them back into the source files, so the tests were trivial to keep around.

File: objfile/patterns.go (hunk 2 above)
Comment (stevemk14ebr) [reply objfile/patterns.go:45]: I agree it's (probably) not a hot path worth optimizing, I was just curious on the effect it would have.

File: build_all.sh
Comment (stevemk14ebr) [reply build_all.sh:1]: thanks!

**Comment by stevemk14ebr** [comment]
Sounds good. Let me know if you'd like to discuss this first before you put too much work in. It's possible we may be able to re-visit the core algorithm itself. I've focused on correctness so far, optimizations have been mostly ignored till now except for when necessary to keep performance acceptable.

**Comment by williballenthin** [comment]
great, will do. i had thought i would have time immediately but there's a lot of GSoC stuff to close out. will do this as soon as i can since i think this will help VT.

**Comment by stevemk14ebr** [comment]
I had an idea for a possible optimization we could try. I read a blog by burntsushi a while ago on techniques he utilized for efficient regex searching in his library. One of simple techniques used was to not start a regex scan until after first performing a fast prefix scan to create a candidate match set, we should try this. We could adapt the yara to regex routine to extract the 'longest fixed sequence' of bytes per pattern and scan over all file bytes once per pattern matching this sequence, and return a candidate regex match of length [-len(regex), len(regex)]. We then perform binary regex over these candidates. We use a window of negative length to support when the 'longest fixed sequence' is in the middle of a pattern rather than the start.

This makes an assumption that the binary regex crate does not already do this, or even if it does then the second assumption that go's memcmp would be faster than the compare the regex crate does over enough data. 

A second issue we have is that we have multiple patterns. A hopefully easy solution would be to somehow reliably determine which arch (independent of os) a binary is using and only scan for that pattern. If we cannot do that reliably then we will need to experiment on if we should do multiple candidate regex scans over the data per signature or scan once with multiple comparisons at each step.

Thoughts?

**Comment by williballenthin** [comment]
1. use only candidate arch patterns - yup, agree.
  2. use pre scan to identify candidate matches - yup, also agree. 

For (2) we know from one of the other PRs that Go's string.Index() routine is very fast, so I do expect this to be a lot faster than the regex logic. 

When making changes in this part of the code I don't feel very confident because I'm not sure if any test cases cover these scenarios. Can you confirm and/or can we find a few more sample files to exercise the pattern scanning functionality?

**Comment by stevemk14ebr** [comment]
This feature exists mostly to combat `garble`. I generate test binaries with `garble build -ldflags="-w -s"`

**Comment by stevemk14ebr** [comment]
I've implemented the needle optimization, it seems to have large increases to performance based on limited empirical testing :smile:

Need to do more testing and benchmarking still but _seems_ like a win!

**Comment by stevemk14ebr** [comment]
After fixing up the dataAfterSection cache to work for all OS's we get another 3x speedup:

```
File: GoReSym.test
Type: cpu
Time: Aug 15, 2023 at 1:32pm (EDT)
Duration: 11.05s, Total samples = 10.89s (98.55%)
Showing nodes accounting for 8.78s, 80.62% of 10.89s total
Dropped 267 nodes (cum <= 0.05s)
      flat  flat%   sum%        cum   cum%
         0     0%     0%      9.62s 88.34%  testing.tRunner
         0     0%     0%      9.60s 88.15%  github.com/mandiant/GoReSym.TestAllVersions.func1
         0     0%     0%      9.60s 88.15%  github.com/mandiant/GoReSym.main_impl
         0     0%     0%      4.88s 44.81%  github.com/mandiant/GoReSym/objfile.(*Entry).ParseTypeLinks
         0     0%     0%      4.88s 44.81%  github.com/mandiant/GoReSym/objfile.(*File).ParseTypeLinks (inline)
         0     0%     0%      4.79s 43.99%  github.com/mandiant/GoReSym/objfile.(*Entry).ParseType
     0.08s  0.73%  0.73%      4.72s 43.34%  github.com/mandiant/GoReSym/objfile.(*Entry).ParseType_impl
     0.01s 0.092%  0.83%      2.55s 23.42%  os.(*File).ReadAt
     0.01s 0.092%  0.92%      2.54s 23.32%  io.(*SectionReader).ReadAt
     0.01s 0.092%  1.01%      2.53s 23.23%  os.(*File).pread (inline)
     0.05s  0.46%  1.47%      2.52s 23.14%  internal/poll.(*FD).Pread
         0     0%  1.47%      2.37s 21.76%  github.com/mandiant/GoReSym/objfile.(*Entry).PCLineTable
         0     0%  1.47%      2.37s 21.76%  github.com/mandiant/GoReSym/objfile.(*File).PCLineTable (inline)
         0     0%  1.47%      2.36s 21.67%  syscall.Pread (inline)
     0.01s 0.092%  1.56%      2.36s 21.67%  syscall.pread
     0.01s 0.092%  1.65%      2.35s 21.58%  syscall.Syscall6
     2.10s 19.28% 20.94%      2.10s 19.28%  runtime/internal/syscall.Syscall6
         0     0% 20.94%      2.10s 19.28%  syscall.RawSyscall6
         0     0% 20.94%      2.01s 18.46%  github.com/mandiant/GoReSym/objfile.(*Entry).ModuleDataTable
         0     0% 20.94%      2.01s 18.46%  github.com/mandiant/GoReSym/objfile.(*File).ModuleDataTable
     0.43s  3.95% 24.89%      1.97s 18.09%  runtime.mallocgc
     0.01s 0.092% 24.98%      1.72s 15.79%  github.com/mandiant/GoReSym/objfile.(*Entry).readRTypeName
     0.20s  1.84% 26.81%      1.70s 15.61%  bytes.Index
     0.02s  0.18% 27.00%      1.19s 10.93%  github.com/mandiant/GoReSym/objfile.(*elfFile).read_memory
         0     0% 27.00%      1.09s 10.01%  runtime.systemstack
     0.02s  0.18% 27.18%      1.04s  9.55%  github.com/mandiant/GoReSym/objfile.(*peFile).read_memory
         0     0% 27.18%      1.02s  9.37%  github.com/mandiant/GoReSym/objfile.findModuleInitPCHeader
         0     0% 27.18%      0.95s  8.72%  github.com/mandiant/GoReSym/objfile.FindRegex
         0     0% 27.18%      0.82s  7.53%  bytes.IndexByte (inline)
         0     0% 27.18%      0.82s  7.53%  github.com/mandiant/GoReSym/objfile.(*elfFile).pcln
         0     0% 27.18%      0.82s  7.53%  github.com/mandiant/GoReSym/objfile.(*elfFile).pcln_scan
         0     0% 27.18%      0.80s  7.35%  github.com/mandiant/GoReSym/objfile.findAllOccurrences
         0     0% 27.18%      0.79s  7.25%  github.com/mandiant/GoReSym/objfile.(*elfFile).moduledata_scan
     0.77s  7.07% 34.25%      0.77s  7.07%  indexbytebody
     0.02s  0.18% 34.44%      0.75s  6.89%  runtime.makeslice
     0.01s 0.092% 34.53%      0.70s  6.43%  runtime.growslice
     0.69s  6.34% 40.86%      0.69s  6.34%  runtime.memmove
         0     0% 40.86%      0.67s  6.15%  github.com/mandiant/GoReSym/objfile.(*peFile).moduledata_scan
     0.67s  6.15% 47.02%      0.67s  6.15%  runtime.memclrNoHeapPointers
     0.03s  0.28% 47.29%      0.62s  5.69%  encoding/binary.Read
         0     0% 47.29%      0.59s  5.42%  runtime.gcBgMarkWorker
         0     0% 47.29%      0.56s  5.14%  github.com/mandiant/GoReSym/objfile.(*machoFile).pcln
         0     0% 47.29%      0.56s  5.14%  github.com/mandiant/GoReSym/objfile.(*machoFile).pcln_scan
     0.01s 0.092% 47.38%      0.55s  5.05%  github.com/mandiant/GoReSym/objfile.(*elfFile).symbols
         0     0% 47.38%      0.53s  4.87%  github.com/mandiant/GoReSym/objfile.(*machoFile).moduledata_scan
     0.05s  0.46% 47.84%      0.53s  4.87%  github.com/mandiant/GoReSym/objfile.(*machoFile).symbols
         0     0% 47.84%      0.50s  4.59%  github.com/mandiant/GoReSym/debug/gosym.NewTable
         0     0% 47.84%      0.49s  4.50%  github.com/mandiant/GoReSym/objfile.(*peFile).pcln
         0     0% 47.84%      0.49s  4.50%  github.com/mandiant/GoReSym/objfile.(*peFile).pcln_scan
     0.02s  0.18% 48.03%      0.47s  4.32%  github.com/mandiant/GoReSym/objfile.(*machoFile).read_memory
         0     0% 48.03%      0.47s  4.32%  runtime.gcBgMarkWorker.func2
     0.01s 0.092% 48.12%      0.47s  4.32%  runtime.gcDrain
         0     0% 48.12%      0.44s  4.04%  github.com/mandiant/GoReSym/debug/elf.(*File).Symbols (inline)
         0     0% 48.12%      0.44s  4.04%  github.com/mandiant/GoReSym/debug/elf.(*File).getSymbols
         0     0% 48.12%      0.40s  3.67%  fmt.Sprintf
     0.37s  3.40% 51.52%      0.38s  3.49%  internal/bytealg.IndexRabinKarpBytes
     0.03s  0.28% 51.79%      0.33s  3.03%  runtime.concatstrings
     0.07s  0.64% 52.43%      0.32s  2.94%  encoding/binary.(*decoder).value
     0.10s  0.92% 53.35%      0.32s  2.94%  runtime.scanobject
         0     0% 53.35%      0.31s  2.85%  runtime.(*pageAlloc).scavenge
         0     0% 53.35%      0.31s  2.85%  runtime.(*pageAlloc).scavenge.func1
         0     0% 53.35%      0.31s  2.85%  runtime.(*pageAlloc).scavengeOne
         0     0% 53.35%      0.31s  2.85%  runtime.(*scavengerState).init.func2
         0     0% 53.35%      0.31s  2.85%  runtime.(*scavengerState).run
         0     0% 53.35%      0.31s  2.85%  runtime.bgscavenge
     0.06s  0.55% 53.90%      0.29s  2.66%  runtime.heapBitsSetType
         0     0% 53.90%      0.29s  2.66%  runtime.sysUnused
     0.01s 0.092% 53.99%      0.29s  2.66%  runtime.sysUnusedOS
     0.01s 0.092% 54.09%      0.28s  2.57%  runtime.concatstring2
     0.28s  2.57% 56.66%      0.28s  2.57%  runtime.madvise
         0     0% 56.66%      0.27s  2.48%  github.com/mandiant/GoReSym/debug/elf.(*File).DataAfterSection
     0.02s  0.18% 56.84%      0.27s  2.48%  runtime.newobject (partial-inline)
     0.02s  0.18% 57.02%      0.26s  2.39%  github.com/mandiant/GoReSym/debug/gosym.(*LineTable).go12Funcs
         0     0% 57.02%      0.26s  2.39%  github.com/mandiant/GoReSym/objfile.(*Entry).ReadPointerSizeMem
     0.03s  0.28% 57.30%      0.25s  2.30%  runtime.slicebytetostring
     0.04s  0.37% 57.67%      0.24s  2.20%  fmt.(*pp).doPrintf
         0     0% 57.67%      0.24s  2.20%  github.com/mandiant/GoReSym/debug/elf.(*File).getSymbols64
         0     0% 57.67%      0.23s  2.11%  github.com/mandiant/GoReSym/debug/gosym.(*LineTable).go12MapFiles
     0.02s  0.18% 57.85%      0.23s  2.11%  runtime.memclrNoHeapPointersChunked
         0     0% 57.85%      0.22s  2.02%  runtime.schedule
     0.21s  1.93% 59.78%      0.21s  1.93%  indexbody
```

**Comment by williballenthin** [comment]
good catch on the dataAfterSection issue. that was obviously an oversight and I apologize for introducing the bug.

**Comment by stevemk14ebr** [comment]
no worries, i've introduced plenty of bugs xD

**Comment by stevemk14ebr** [comment]
At this point I think this is ready to merge 😄 I've implemented an additional optimization that's been needing for a while know to avoid re-parsing all the pclntab candidates the second time through. Then I found the underlying bug which you had reported when parsing `kubectl` and fixed that. That issue was two parts:

1. When we scan the pclntab candidates the first time through, we expect that finding a moduledata with the pclntab VA means that we have the correct candidate. This assumption was wrong, because we were using the optionally present binary symbols to locate the moduledata. When these symbols were valid, the pclntab VA was in fact not being verified leaving us with the wrong candidate in some situations. I've simply removed this branch so that we always scan for the moduledata using the pclntab VA so that this assumption is now true. This is _slightly_ slower but ultimately more correct and simpler code.

2. With very large binaries >= uint16_max function counts we'd hit an OOM guard that I'd added prior. Wild enough there does exist Go binaries in the wild with 100k plus functions, I've 3x-ed this limit to fix. The `kubectl` binary has ~100k functions 🤯

**Comment by stevemk14ebr** [comment]
https://github.com/mandiant/GoReSym/pull/36 forgot to push these
